### ISSUE TITLE
Updates for September 11 beta launch

### ISSUE THREAD

**Issue by chrismaskell** [neurohub/neurohub#15]
[Critical updates to do before Sept. 11 NeuroHub beta launch](https://docs.google.com/document/d/19jXhYKsXCLHowdO-AwJxuUctljBQ5lIMvm1EwULV93I/edit?usp=sharing)

**Comment by 3design** [comment]
I have gone though the document and made the following changes: 

NeuroHub - Beta Release - website modifications

Portal Page

https://neurohub.ca/portal.html

Portal icons to update from “Alpha” to “Beta” ✅

Remove text “Requires McGill VPN if working remotely” ✅

Feature list update:

Correct spelling of simultaneously ✅

Update the “Open Portal” button from “Alpha” to “Beta” ✅
Update the link for it to:

https://portal.neurohub.ca ✅

Update contact email message from:

“Contact info@neurohub.ca for any issues” to 

“Contact support@neurohub.ca for any issues” ✅

New header:
Beta access
To request access to the NeuroHub beta, follow the “Open Portal” button above. Once on the NeuroHub Portal page, click “Request an Account” in the bottom-right to request beta access. The NeuroHub team will review your request as soon as possible. ✅

**Comment by 3design** [comment]
In addition I have done a search/replace for info@ and revised to support@

**Comment by 3design** [comment]
linked documents navigation to this wiki

**Comment by chrismaskell** [comment]
All Documentation links in top menu bar point to this wiki except  when you're on neurohub.ca homepage?

**Comment by 3design** [comment]
Sorry this was an error on my local system. I've updated just now and it should be live in the next few minutes
