### ISSUE TITLE
Neurohub documentation display error (Firefox only)

### ISSUE THREAD

**Issue by prioux** [neurohub/neurohub#18]
This issue was originally reported by Alex Hutton in https://github.com/aces/cbrain/issues/1009 (which has been closed).

See the screenshot and description of the issue over there.

**Comment by 3design** [comment]
@adora07 This no longer seems relevant. I recommend closing this issue if that's the case

**Comment by adora07** [comment]
@prioux @AlexandreHutton Can you advise if this issue is still relevant?

**Comment by AlexandreHutton** [comment]
The display error is the same as described in the original issue.

**Comment by AlexandreHutton** [comment]
From [here](https://github.com/aces/cbrain/issues/1009#issuecomment-769827867):  
> the documentation page has been moved to the github wiki. the documentation.html page is left on the repo for the purpose of an archive however if this is confusing, I can remove the html page so that it is no longer available. Anyone have thoughts about this?  
  
Redirect to the correct documentation. That page is the first results that comes up "neurohub ukbb." It should not be left up.

**Comment by 3design** [comment]
I have added a new header in documentation.html to warn users that the page has moved. Additionally I have set a redirect for 15 seconds to the new page, as well as a link in case JS is disabled in browser. Changes should show up in 10 minutes on neurohub.ca/documentation.html

**Comment by adora07** [comment]
@AlexandreHutton please verify and close if it is now resolved

**Comment by AlexandreHutton** [comment]
I can't close the issue since I'm not assigned to it, I didn't open it, and I don't have the relevant permissions for this repo.

**Comment by 3design** [comment]
Issue closed for now. Any further changes can be a new issue.
