### ISSUE TITLE
Documentation page still contains links to the old port 5000 installation

### ISSUE THREAD

**Issue by prioux** [neurohub/neurohub#19]
The port 5000 installation was a development installation. It's been decommissioned now.

But the documentation in the neurohub website page still has links to it, in the collapsible blue section `To request access to the UK Biobank data through the NeuroHub platform`

**Comment by 3design** [comment]
Hi Pierre. Are you looking at the documentation in the wiki here: https://github.com/neurohub/neurohub_documentation/wiki ?

**Comment by prioux** [comment]
I can't find this anymore, so I guess the documentation has changed since I created this issue.
