### ISSUE TITLE
Update of homepage text/about page

### ISSUE THREAD

**Issue by chrismaskell** [neurohub/neurohub#20]
Change body text on neurohub.ca/index to:

**An Open Science infrastructure for reproducible, collaborative and multidisciplinary research**

NeuroHub allows access to powerful computational tools for data processing and streamlined systems for secure storage and sharing of multi-disciplinary data. Integrating multimodal data with advanced analysis algorithms allows users to:

-     Securely store and share multi-modal data for multi-disciplinary collaborative research
-     Execute advanced searches on raw and processed data from the UK Biobank
-     Launch small interactive and large-scale computational workflows and import results into NeuroHub
-     Develop machine learning algorithms through big data in NeuroHub

Add onto the end of neurohub.ca/about:

In keeping with McGill’s commitment to Open Science, the NeuroHub will extend the FAIR principles (Findable, Accessible, Interoperable, Reusable) and lead the development of international neuroinformatics standards and best practices.

**Comment by 3design** [comment]
updated master with the above changes
