### ISSUE TITLE
Event Page: archive old events and creation of 2 new events

### ISSUE THREAD

**Issue by adora07** [neurohub/neurohub#22]
https://neurohub.ca/events.html

Please archive the 3 events currently there and replace with 2 new events:

**NeuroHub Seminar - Intro to NeuroHub**
Date: November 10, 2020 @ 10-11am
Body:
Speaker: Dr. Jean-Baptiste Poline & Dr. Bryan Caron
Location: zoom link will be provided to registered attendees 1 day before the event
Free event: Open to faculty, staff and students from McGill University, and all members of the Healthy Brains, Healthy Lives community
Summary
NeuroHub is an open platform that offers tools for efficient, collaborative and reproducible science in neuroinformatics, genomics, social sciences, biology and more. NeuroHub gives users access to streamlined systems for secure storage and sharing of multi- disciplinary data and powerful computational tools for data processing.
In this seminar presentation, an introduction and overview of the NeuroHub vision and platform will be given, with reference to the platform components which together enable science at scale. Current and future features and functionalities of NeuroHub will be described, along with upcoming opportunities for members of the research community to gain hands-on experience with NeuroHub.
Speakers
Dr. Jean-Baptiste Poline, Associate Professor, Neurology and Neurosurgery, McGill University
Dr. Bryan Caron, Director, Operations and Development, NeuroHub

**NeuroHub Training Session - Fundamentals of the NeuroHub Platform**
Date: November 13, 9:30am-12:30pm
Body: to be provided

**Comment by adora07** [comment]
Here is the information for the NeuroHub Training Session. @3design can you update the event?

**NeuroHub Training Session - Fundamentals of the NeuroHub Platform**
Tue, November 17, 2020
1:30 PM – 4:30 PM EST

Speakers: The NeuroHub Team

Location: zoom link will be provided to registered attendees 1 day before the event

Free event: Open to faculty, staff and students from McGill University, and all members of the Healthy Brains, Healthy Lives community

Summary

In this workshop, participants will gain hands-on, interactive experience with the fundamental components of NeuroHub through a series of practical exercises on your own computer. Participants will work both individually and in groups during the workshop.

The topics that will be covered in this first training session will include the following:

_**Introduction and Overview of NeuroHub and associated components**

- The NeuroHub UI and Dashboard

**Projects and Data Handling in NeuroHub**

- Data Input / Output

- Data Sharing

**Task Launching in NeuroHub**

- data and application selection

- task monitoring

- accessing data results_

By completing this training workshop, participants will be able to continue their exploration of more advanced concepts and elements of NeuroHub to be covered in future workshops.

About

NeuroHub is an open platform that offers tools for efficient, collaborative and reproducible science in neuroinformatics, genomics, social sciences, biology and more. NeuroHub gives users access to streamlined systems for secure storage and sharing of multi- disciplinary data and powerful computational tools for data processing.

**Comment by 3design** [comment]
will do!
