### ISSUE TITLE
Add recording to NeuroHub Seminar - Intro to NeuroHub

### ISSUE THREAD

**Issue by adora07** [neurohub/neurohub#32]
Recording link: https://mcgill.zoom.us/rec/play/f8ZnHGLVR3n8TImyjGXZIdxdX6fuvPXG7JzF85B2cjLhdCdTbz7udke4C-YGY8VsWyIOlM1QRVdk-tZR.m2nNWpOgR2BajVB1?continueMode=true&_x_zm_rtaid=CfLhg1ABQL-4fj2VMfx0SA.1605025548205.2424d509aa5c56728a76abdab9e86940&_x_zm_rhtaid=997

@3design if there is a better alternative to posting the zoom link (such as exporting it somehow), I look to you for your recommendation!

**Comment by adora07** [comment]
@chrismaskell can you put the recording link here when ready?

**Comment by chrismaskell** [comment]
Here's the recording link: https://www.youtube.com/watch?v=JfpWqY2KrKo

This event item should also now be moved to Past Events and the registration link should be removed
