### ISSUE TITLE
Add New Event: NeuroHub Training Session - Advanced Concepts of the NeuroHub Platform

### ISSUE THREAD

**Issue by adora07** [neurohub/neurohub#33]
Follow same formatting as other event pages. Registration link will be available Nov 11.

NeuroHub Training Session - Advanced Concepts of the NeuroHub Platform
Date: tbc
Speakers: The NeuroHub Team

Location: zoom link will be provided to registered attendees 1 day before the event

Free event: Open to faculty, staff and students from McGill University, and all members of the Healthy Brains, Healthy Lives community

Summary

In this workshop, participants will gain hands-on, interactive experience with the advanced components of NeuroHub through a series of practical exercises on your own computer. Participants will work both individually and in groups during the workshop.

The topics that will be covered in this second training session will include the following:

- LORIS Data Query Tool (DQT) concepts and interactions with NeuroHub (UI)

- Using the CBRAIN API

- NeuroHub and JupyterHub Notebooks

By completing this training workshop, participants will be able to continue their exploration of more advanced concepts and elements of NeuroHub, and learn to leverage the advanced capabilities of the API for data exploration and analysis.

About

NeuroHub is an open platform that offers tools for efficient, collaborative and reproducible science in neuroinformatics, genomics, social sciences, biology and more. NeuroHub gives users access to streamlined systems for secure storage and sharing of multi- disciplinary data and powerful computational tools for data processing.

**Comment by 3design** [comment]
will need the registration link when it is available.

**Comment by jbpoline** [comment]
The registration is limited to a specific list of participants, we probably
do not want the link to be accessible to all ?

**Comment by adora07** [comment]
@3design Here is the eventbrite link for inclusion

https://www.eventbrite.ca/e/neurohub-training-session-advanced-concepts-of-the-neurohub-platform-tickets-128037279951

**Comment by 3design** [comment]
also moved nov events to past section

**Comment by adora07** [comment]
The event has been rescheduled to:

January 6 @ 1:30-4:30pm

Same agenda, same registration link.
