### ISSUE TITLE
Our Vision Page

### ISSUE THREAD

**Issue by chrismaskell** [neurohub/neurohub#35]
Page is now redundant and can be removed/archived

**Comment by jbpoline** [comment]
@chrismaskell  Which page is it redundant with ?  I agree this should be reworked or removed though - this is text from 2 years ago

**Comment by chrismaskell** [comment]
@jbpoline I've done some more editing of the About page (just added a new comment to that issue) and I think the most critical info has been included on that page now from the Our Vision page.
