### ISSUE TITLE
Update Advanced Training Event

### ISSUE THREAD

**Issue by 3design** [neurohub/neurohub#41]
As per @bryancaron request, update the Advaced Training Event to reflect date and time.

**Comment by adora07** [comment]
@3design Just noticed a correction needed to the body of the event. We can close the issue once corrected.

<img width="670" alt="Screen Shot 2020-12-03 at 11 30 14 AM" src="https://user-images.githubusercontent.com/44646677/101058547-3e647880-355b-11eb-92ad-42baf20c4bf4.png">
