### ISSUE TITLE
Add McGill Initiative for Computational Medicine Event

### ISSUE THREAD

**Issue by jbpoline** [neurohub/neurohub#44]
JB Poline will be presenting the NeuroHub and CONP infrastructures on Thursday Dec 9th at 3pm

https://www.eventbrite.ca/e/research-day-tickets-129015848877

**Comment by 3design** [comment]
Sorry looks like this was overlooked. Should I add this to the events page still?

**Comment by adora07** [comment]
@jbpoline Please advise

**Comment by jbpoline** [comment]
@3design  can we put in "Past events" ?

**Comment by 3design** [comment]
updated with event card in past events - link goes to registration and agenda page.
