### ISSUE TITLE
Addition of NeuroHub technical paper publications page to the website

### ISSUE THREAD

**Issue by bryancaron** [neurohub/neurohub#45]
Hi Derek,

As per what was communicated by email earlier on in discussions with Alan, we would like to have a page created on the NeuroHub website where we would be able to list the various NeuroHub technical publications as well as provide direct links to the publications.

At the moment all such papers have been stored in our shared Google drive (NeuroHub_Team-Documents --> NeuroHub Technical Papers,with the Word-file containing the list.  The PDF files correspond to the documents listed.

Can you please create a Publications page on the NeuroHub site where these can be listed.  This would be an easy reference we would share with collaborators and others.

A more elaborate page for publications that do things like tie into DOIs and ORCID which we still have to discuss with Darcy and yourself would be a future, separate topic.

Please let me know if you have any questions.  Thanks.

Bryan.

**Comment by bryancaron** [comment]
Provided additional information in follow-up direct message on January 12.

**Comment by 3design** [comment]
This page cannot be accessed from the regular navigation yet. Instead use hard-link: neurohub.ca/references.html. Once checked, I will connect it to all other pages.
