### ISSUE TITLE
Add Upcoming Event: NeuroHub Training Session

### ISSUE THREAD

**Issue by adora07** [neurohub/neurohub#50]
Title: Advanced Concepts of the NeuroHub Platform - Data Query Tool
Speakers: The NeuroHub team
Date: February 2021 (tbc)

**details to follow**

**Comment by 3design** [comment]
updated - waiting for further details

**Comment by adora07** [comment]
Thank you. Will update here once further details are available!

**Comment by adora07** [comment]
@3design Please update with the following information from the Eventbrite, and include link for registration

https://www.eventbrite.ca/e/neurohub-training-session-advanced-concepts-data-query-tool-tickets-141193209691
