### ISSUE TITLE
Embed Video recording & move to past events: NeuroHub Seminar Series (March 8)

### ISSUE THREAD

**Issue by adora07** [neurohub/neurohub#52]
Video recording:   https://www.youtube.com/watch?v=GNReMZNGy8o

Please format in the same way as for other event pages.

**Comment by 3design** [comment]
looking at this now

**Comment by adora07** [comment]
@3design Looks great, but would you mind adding on the full event info to be consistent in event page formatting. I do realize I didn't provide this info before, so my bad! See below for the information.

NeuroHub Seminar Series - Metadata Annotations and Provenance with Linked Data Technologies in Human Neuroscience

Monday, March 8, 2021 
2:00 - 3:00PM EDT

Speaker: Dr. David Keator, UCI Neuroscience Imaging Center (invited by Dr. Jean-Baptiste Poline)

Abstract
Efficient use of existing data relies on (meta)data being FAIR: Findable, Accessible, Interoperable and Reusable. A critical barrier to FAIR data is that metadata descriptions vary widely in degree of detail and are inconsistent in terminologies used, making neuroscience data often not reusable without significant interactions with the original authors. This lack of consistent metadata makes comparisons and integration of data across studies and sites difficult. To facilitate search across datasets we developed the Neuroimaging Data model (NIDM), built using linked-data techniques to unambiguously describe experimental data, workflows, and results. In this talk I will introduce linked-data techniques and how they’re being used in neuroscience to support un-ambiguous descriptions of data, workflows, and to facilitate query and data integration across unrelated studies.

Speaker Bio
Dr. Keator has been an active researcher in the fields of neuroimaging and neuroinformatics applied to psychiatric and neurological disorders for over twenty years. His research has been focused in three principle domains: (1) Identifying brain-based biomarkers of dementia in Down Syndrome, traumatic brain injury (TBI), Schizophrenia, and Alzheimer’s disease; (2) The development of advanced machine learning models for problems in neuroimaging and medicine; (3) Developing biomedical informatics tools and techniques for the field of neuroimaging and applying them to problems in medicine. In each of these domains he have made significant research contributions, many of which have gained international exposure. Since 2011, Dr. Keator has chaired the Neuroimaging Data Model (NIDM) working group consisting of representatives form 12 institutions across Europe and the United States and co-developed the metadata standard. He is an active member of the International NeuroInformatics Coordinating Facility (INCF) Neuroimaging Task Force, served on the Neuroimaging Technology Initiative’s data format working group responsible for the development of the NIfTI-1 standard, and the informatics director for the UCI Conte Center, developing informatics tools to support translational research. Further, Dr. Keator is the technical and operations director of the UCI Neuroscience Imaging Center, responsible for PET and MRI research performed at the center, quality control, reconstruction, and statistical analysis.

**Comment by adora07** [comment]
Thank you!
