### ISSUE TITLE
Updates to Team page

### ISSUE THREAD

**Issue by adora07** [neurohub/neurohub#56]
1. Move Candice Czech, Giulia Ippoliti, Liam O'Callaghan and Alexandre Hutton to Past Collaborators section
2. Update Title for Samir Das: Associate Director of Technology
3. Add the following new team members (will provide photo when available)

Verena Schuster, Research Assistant
Sebastian Urchs, Research Software Developer
Adam Trefonides, Research Software Developer

**Comment by 3design** [comment]
waiting for additional images
