### ISSUE TITLE
embedding dashboard into website

### ISSUE THREAD

**Issue by bryancaron** [neurohub/neurohub#58]
Hi Derek,

Together with Diana we have built various dashboards for reporting information at different levels (management, public).This is done using Smartsheet.

One pubic dashboard for the NeuroHub project has been requested by Alan to be made visible via the website.  This is a supported element within Smartsheet as per the documentation link below.

Can we please follow-up to discuss so that this is implemented and embedded in the site? Ideally this would by June 11 so as to be ready for presentation by Alan and myself the following week.

https://help.smartsheet.com/articles/522078-publishing-smartsheet-items

Thanks.

Best regards,

Bryan.

**Comment by 3design** [comment]
@bryancaron I will need access to smartsheet or the iframe code generated by smartsheet to be able to embed this in a webpage
