### ISSUE TITLE
NeuroHub styling (capitalization)

### ISSUE THREAD

**Issue by MontrealSergiy** [neurohub/neurohub#6]
on the same page NeurohHub is styled differently, e.g. in the mission text and about menu drop down it occurs as Neurohub. ~~Sometime in the same sentence it goes with and without the article, "Once the NeuroHub platform is online, scientists will be able to use NeuroHub to access"~~

updated: I remove the part about the article

**Comment by adora07** [comment]
@MontrealSergiy do you mean when it is referred to as "NeuroHub platform" and other times it is referred to as "NeuroHub"?

**Comment by 3design** [comment]
I believe the meaning is the consistency of use in

Neurohub and NeuroHub

Which are we going to use?

**Comment by MontrealSergiy** [comment]
correct @3design should be uniform.  I think one with capital H looks better

**Comment by MontrealSergiy** [comment]
I remove `article` criticism, `the` is because of `platform`.  In my mother language there are no articles so I am never sure where to use them or skip.

**Comment by adora07** [comment]
it needs to be NeuroHub (capital H)
