### ISSUE TITLE
Corrections to References page

### ISSUE THREAD

**Issue by adora07** [neurohub/neurohub#61]
1. Functionality: Is there a way to keep the lists expanded until the user closes it? Currently, if you expand one list, and then go to expand the other list, the previous section will collapse. (using the plus sign)

2. First paper in Research Outcomes belongs in Technical Papers -- please move
(Pierre Rioux, Gregory Kiar, Alexandre Hutton, Alan C. Evans, and Shawn T. Brown. 2020 Deploying large fixed file datasets with SquashFS and Singularity. PEARC ’20: Practice and Experience in Advanced Research Computing doi)

3. For consistency, have all links to articles say “read the paper”

4. Remove duplicate paper from 2021: Jennifer Tremblay-Mercier, Cécile Madjar, Samir Das, Alexa Pichet Binette, Stephanie O.M. Dyke, Pierre Étienne, Marie-Elyse Lafaille-Magnan, Jordana Remz, Pierre Bellec, D. Louis Collins, M. Natasha Rajah, Veronique Bohbot, Jeannie-Marie Leoutsakos, Yasser Iturria-Medina, Justin Kat, Richard D. Hoge, Serge Gauthier, Christine L. Tardif, M. Mallar Chakravarty, Jean-Baptiste Poline, Pedro Rosa-Neto, Alan C. Evans, Sylvia Villeneuve, Judes Poirier, John C. S. Breitner, the PREVENT-AD Research Group Open Science Datasets from PREVENT-AD, a Longitudinal Cohort of Pre-symptomatic Alzheimer’s Disease. bioRxiv 2020.03.04.976670 doi

**Comment by 3design** [comment]
- [ ] Functionality: Is there a way to keep the lists expanded until the user closes it? Currently, if you expand one list, and then go to expand the other list, the previous section will collapse. (using the plus sign)

- [x] First paper in Research Outcomes belongs in Technical Papers -- please move

(Pierre Rioux, Gregory Kiar, Alexandre Hutton, Alan C. Evans, and Shawn T. Brown. 2020 Deploying large fixed file datasets with SquashFS and Singularity. PEARC ’20: Practice and Experience in Advanced Research Computing doi)

- [x] For consistency, have all links to articles say “read the paper”

- [x] Remove duplicate paper from 2021: Jennifer Tremblay-Mercier, Cécile Madjar, Samir Das, Alexa Pichet Binette, Stephanie O.M. Dyke, Pierre Étienne, Marie-Elyse Lafaille-Magnan, Jordana Remz, Pierre Bellec, D. Louis Collins, M. Natasha Rajah, Veronique Bohbot, Jeannie-Marie Leoutsakos, Yasser Iturria-Medina, Justin Kat, Richard D. Hoge, Serge Gauthier, Christine L. Tardif, M. Mallar Chakravarty, Jean-Baptiste Poline, Pedro Rosa-Neto, Alan C. Evans, Sylvia Villeneuve, Judes Poirier, John C. S. Breitner, the PREVENT-AD Research Group Open Science Datasets from PREVENT-AD, a Longitudinal Cohort of Pre-symptomatic Alzheimer’s Disease. bioRxiv 2020.03.04.976670 doi

**Comment by adora07** [comment]
1. This duplicate was removed, but the paper should be listed under the year 2020. It is currently under 2021.
Jennifer Tremblay-Mercier, Cécile Madjar, Samir Das, Alexa Pichet Binette, Stephanie O.M. Dyke, Pierre Étienne, Marie-Elyse Lafaille-Magnan, Jordana Remz, Pierre Bellec, D. Louis Collins, M. Natasha Rajah, Veronique Bohbot, Jeannie-Marie Leoutsakos, Yasser Iturria-Medina, Justin Kat, Richard D. Hoge, Serge Gauthier, Christine L. Tardif, M. Mallar Chakravarty, Jean-Baptiste Poline, Pedro Rosa-Neto, Alan C. Evans, Sylvia Villeneuve, Judes Poirier, John C. S. Breitner, the PREVENT-AD Research Group Open Science Datasets from PREVENT-AD, a Longitudinal Cohort of Pre-symptomatic Alzheimer’s Disease. bioRxiv 2020.03.04.976670 read the paper

2. There are still 2 references that read "doi" under NeuroHub Technical Papers. The 1 and 3 article under year 2020.

**Comment by 3design** [comment]
I've updated the page again to remove the doi and also move the reference to the correct year

**Comment by adora07** [comment]
> I've updated the page again to remove the doi and also move the reference to the correct year

Perfect for those 2 items!

**Comment by adora07** [comment]
closing because the website has been updated, and this issue is no longer valid.
