### ISSUE TITLE
Add pointer to NeuroHub acknowlegments

### ISSUE THREAD

**Issue by adora07** [neurohub/neurohub#68]
To be more easily accessible for users, we would like to place a direct pointer to the NeuroHub acknowledgements wiki page on the Getting Started page (https://neurohub.ca/get-started/).

The button or link to NeuroHub Acknowledgements (https://github.com/neurohub/neurohub_documentation/wiki/7.0.Acknowledging-NeuroHub) should be less prominent than the items already there, but still visible for users.

**Comment by 3design** [comment]
@adora07 I have added a link under the wiki documentation link so that a user can go directly to the acknowledgements from there. Please let me know if this is okay.

**Comment by jbpoline** [comment]
Thanks for that Derek @3design  !

**Comment by adora07** [comment]
@3design Please re-title the link "How to Acknowledge NeuroHub"

**Comment by 3design** [comment]
@adora07 Updated!

**Comment by adora07** [comment]
Looks good. Thank you!
