### ISSUE TITLE
a minor grammar and style question

### ISSUE THREAD

**Issue by MontrealSergiy** [neurohub/neurohub#7]
I am not completely sure of the verb-noun and pronoun-noun agreement for the Neurohub community. While various dialects and style guides have a different stance on agreement of collective nouns, the general rule that agreement should be consistent. however in the following phrase 

> The Neurohub community has need for a web-based portal that allows them

verb `has` is in singular form while the pronoun `them` is plural

**Comment by adora07** [comment]
@MontrealSergiy the grammar is correct, but now that I am re-reading, it is missing a word!

@3design please add the missing word in bold:
The Neurohub community has **a** need for a web-based portal that allows them

**Comment by 3design** [comment]
updated on master > vision.html

**Comment by MontrealSergiy** [comment]
@adora07 That's make me think that at some point website might benefit from a qualified copy-writer or proof reader, or somebody blessed with such skills. 

A decade or two ago I tried commercial grammar checker Antidote but it generated a lot of false positives
